import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  header: {
    backgroundColor: '#ffffff',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 1,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  headerContent: {
    maxWidth: 1280,
    marginHorizontal: 'auto',
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  userAvatar: {
    width: 48,
    height: 48,
    backgroundColor: '#9333ea',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userAvatarText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 16,
  },
  userInfo: {
    marginRight: 16,
  },
  userName: {
    fontWeight: '600',
    color: '#111827',
    fontSize: 14,
  },
  userRole: {
    fontSize: 12,
    color: '#4b5563',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  scrollContent: {
    paddingVertical: 32,
    paddingHorizontal: 16,
    maxWidth: 1280,
    marginHorizontal: 'auto',
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#4b5563',
    marginBottom: 32,
  },
  statsContainer: {
    gap: 16,
    marginBottom: 32,
  },
  statCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  statCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  statIconBox: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statLabel: {
    fontSize: 12,
    color: '#4b5563',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 28,
    fontWeight: '700',
    color: '#111827',
  },
  section: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    paddingHorizontal: 24,
    paddingVertical: 24,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sectionTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  addButton: {
    width: 40,
    height: 40,
    backgroundColor: '#dbeafe',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemList: {
    gap: 8,
  },
  listItem: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
  },
  listItemText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#111827',
  },
  addForm: {
    marginTop: 16,
    gap: 8,
  },
  input: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderColor: '#d1d5db',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    fontSize: 14,
  },
  formButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  submitButton: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#2563eb',
    borderRadius: 8,
    alignItems: 'center',
  },
  submitButtonText: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: '500',
    fontSize: 13,
  },
  cancelButton: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#e5e7eb',
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#374151',
    textAlign: 'center',
    fontWeight: '500',
    fontSize: 13,
  },
  filterContainer: {
    gap: 16,
    marginBottom: 16,
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 8,
  },
  pickerButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderColor: '#d1d5db',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    fontSize: 13,
  },
  pickerButtonText: {
    color: '#111827',
  },
  pickerButtonPlaceholder: {
    color: '#9ca3af',
  },
  dropdown: {
    borderColor: '#d1d5db',
    borderWidth: 1,
    borderRadius: 8,
    marginTop: 8,
    backgroundColor: '#ffffff',
  },
  dropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomColor: '#e5e7eb',
    borderBottomWidth: 1,
  },
  dropdownItemText: {
    fontSize: 13,
    color: '#111827',
  },
  dateInput: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderColor: '#d1d5db',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    fontSize: 13,
  },
  exportButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#16a34a',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  exportButtonText: {
    color: '#ffffff',
    fontWeight: '500',
    fontSize: 13,
  },
  attendanceListHeader: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderBottomColor: '#e5e7eb',
    borderBottomWidth: 1,
  },
  attendanceListTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  emptyState: {
    paddingHorizontal: 24,
    paddingVertical: 48,
    alignItems: 'center',
  },
  emptyStateText: {
    color: '#a3a3a3',
    fontSize: 14,
  },
  attendanceItem: {
    paddingHorizontal: 24,
    paddingVertical: 24,
    borderBottomColor: '#e5e7eb',
    borderBottomWidth: 1,
  },
  attendanceItemHeader: {
    marginBottom: 12,
  },
  attendanceItemName: {
    fontSize: 13,
    fontWeight: '500',
    color: '#111827',
  },
  attendanceItemArea: {
    fontSize: 12,
    color: '#4b5563',
  },
  attendanceItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  attendanceItemPlace: {
    fontSize: 13,
    color: '#4b5563',
  },
  attendanceItemDate: {
    fontSize: 13,
    color: '#4b5563',
  },
  attendanceTimesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  attendanceTime: {
    gap: 4,
  },
  attendanceTimeLabel: {
    fontSize: 11,
    color: '#4b5563',
  },
  attendanceTimeValue: {
    fontSize: 13,
    color: '#111827',
  },
  attendanceBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  attendanceBadgeText: {
    fontSize: 12,
    fontWeight: '500',
  },
  successBadge: {
    backgroundColor: '#dcfce7',
  },
  successBadgeText: {
    color: '#166534',
  },
  pendingBadge: {
    backgroundColor: '#fef3c7',
  },
  pendingBadgeText: {
    color: '#92400e',
  },
});
