import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f9ff',
  },
  header: {
    backgroundColor: '#ffffff',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 1,
  },
  headerContent: {
    maxWidth: 1280,
    marginHorizontal: 'auto',
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  userAvatar: {
    width: 48,
    height: 48,
    backgroundColor: '#2563eb',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userAvatarText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 16,
  },
  userInfo: {
    marginRight: 16,
  },
  userName: {
    fontWeight: '600',
    color: '#111827',
    fontSize: 14,
  },
  userArea: {
    fontSize: 12,
    color: '#4b5563',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  scrollContent: {
    paddingVertical: 32,
    paddingHorizontal: 16,
  },
  clockCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    paddingHorizontal: 32,
    paddingVertical: 32,
    marginBottom: 24,
  },
  clockSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  clockIcon: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#dbeafe',
    borderRadius: 50,
    marginBottom: 16,
  },
  clockTime: {
    fontSize: 56,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  clockDate: {
    color: '#4b5563',
    fontSize: 14,
    textTransform: 'capitalize',
  },
  statusSection: {
    alignItems: 'center',
    marginBottom: 32,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 50,
  },
  statusBadgeInside: {
    backgroundColor: '#dcfce7',
  },
  statusBadgeOutside: {
    backgroundColor: '#fee2e2',
  },
  statusTextInside: {
    fontWeight: '500',
    color: '#15803d',
    fontSize: 13,
  },
  statusTextOutside: {
    fontWeight: '500',
    color: '#991b1b',
    fontSize: 13,
  },
  infoCard: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#f9fafb',
    borderRadius: 12,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  infoLabel: {
    fontSize: 12,
    color: '#4b5563',
    marginBottom: 4,
  },
  infoValue: {
    fontWeight: '500',
    color: '#111827',
    fontSize: 13,
  },
  actionButtons: {
    gap: 16,
    marginBottom: 24,
  },
  actionButtonEntry: {
    backgroundColor: '#16a34a',
    borderRadius: 16,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    paddingHorizontal: 32,
    paddingVertical: 32,
  },
  actionButtonExit: {
    backgroundColor: '#dc2626',
    borderRadius: 16,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    paddingHorizontal: 32,
    paddingVertical: 32,
  },
  actionButtonHistory: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    paddingHorizontal: 32,
    paddingVertical: 32,
    borderColor: '#e5e7eb',
    borderWidth: 2,
  },
  actionButtonContent: {
    alignItems: 'center',
  },
  actionButtonIcon: {
    width: 64,
    height: 64,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  actionButtonText: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 8,
  },
  actionButtonSubtext: {
    fontSize: 13,
  },
  actionButtonTextWhite: {
    color: '#ffffff',
  },
  actionButtonTextGray: {
    color: '#4b5563',
  },
  actionButtonSubtextLight: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  warningCard: {
    backgroundColor: '#fef3c7',
    borderColor: '#fcd34d',
    borderWidth: 2,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  warningContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  warningTitle: {
    fontWeight: '600',
    color: '#b45309',
    marginBottom: 4,
    fontSize: 13,
  },
  warningText: {
    fontSize: 12,
    color: '#92400e',
    flex: 1,
  },
});
