import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  container: {
    maxWidth: 400,
    width: '100%',
  },
  scanningContainer: {
    alignItems: 'center',
  },
  scanFrameContainer: {
    marginBottom: 32,
  },
  scanFrame: {
    width: 256,
    height: 256,
    borderColor: '#60a5fa',
    borderWidth: 4,
    borderRadius: 128,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  progressBar: {
    position: 'absolute',
    height: 4,
    top: '50%',
    left: 0,
    backgroundColor: '#60a5fa',
  },
  scanningCard: {
    backgroundColor: 'rgba(17, 24, 39, 0.8)',
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: 24,
    width: '100%',
  },
  scanningTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 8,
    textAlign: 'center',
  },
  scanningSubtitle: {
    fontSize: 16,
    color: '#93c5fd',
    marginBottom: 16,
    textAlign: 'center',
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  progressText: {
    color: '#9ca3af',
    fontSize: 13,
  },
  successContainer: {
    alignItems: 'center',
  },
  successIconBox: {
    paddingHorizontal: 32,
    paddingVertical: 32,
    backgroundColor: '#10b981',
    borderRadius: 64,
    marginBottom: 32,
  },
  successCard: {
    backgroundColor: 'rgba(17, 24, 39, 0.8)',
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: 24,
    width: '100%',
  },
  successTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#4ade80',
    marginBottom: 8,
    textAlign: 'center',
  },
  successSubtitle: {
    fontSize: 18,
    color: '#ffffff',
    marginBottom: 8,
    textAlign: 'center',
  },
  successDescription: {
    fontSize: 14,
    color: '#9ca3af',
    textAlign: 'center',
  },
  errorContainer: {
    alignItems: 'center',
  },
  errorIconBox: {
    paddingHorizontal: 32,
    paddingVertical: 32,
    backgroundColor: '#ef4444',
    borderRadius: 64,
    marginBottom: 32,
  },
  errorCard: {
    backgroundColor: 'rgba(17, 24, 39, 0.8)',
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: 24,
    width: '100%',
  },
  errorTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#f87171',
    marginBottom: 8,
    textAlign: 'center',
  },
  errorSubtitle: {
    fontSize: 18,
    color: '#ffffff',
    marginBottom: 24,
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: '#374151',
    borderRadius: 8,
  },
  cancelButtonText: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: '500',
    fontSize: 13,
  },
  retryButton: {
    flex: 1,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: '#2563eb',
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: '500',
    fontSize: 13,
  },
  bottomCancelButton: {
    marginTop: 24,
    width: '100%',
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: 'rgba(17, 24, 39, 0.5)',
    borderRadius: 8,
  },
  bottomCancelButtonText: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: '500',
    fontSize: 13,
  },
});
