import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f9ff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  scrollContent: {
    width: '100%',
    maxWidth: 400,
    paddingVertical: 32,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 32,
  },
  iconContainer: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#ffffff',
    borderRadius: 50,
    marginBottom: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  headerSubtitle: {
    color: '#4b5563',
    fontSize: 14,
  },
  credentialsBox: {
    backgroundColor: '#dbeafe',
    borderColor: '#93c5fd',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 24,
  },
  credentialsTitle: {
    fontSize: 12,
    color: '#0c2340',
    fontWeight: '600',
    marginBottom: 8,
  },
  credentialsText: {
    fontSize: 12,
    color: '#1e3a8a',
    marginBottom: 4,
  },
  credentialsBold: {
    fontWeight: '700',
  },
  loginCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    paddingHorizontal: 32,
    paddingVertical: 32,
    marginBottom: 24,
  },
  errorBox: {
    backgroundColor: '#fee2e2',
    borderColor: '#fca5a5',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 16,
  },
  errorText: {
    color: '#b91c1c',
  },
  formContainer: {
    marginBottom: 24,
  },
  inputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 8,
  },
  input: {
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderColor: '#d1d5db',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    fontSize: 14,
  },
  loginButton: {
    width: '100%',
    paddingVertical: 12,
    backgroundColor: '#2563eb',
    borderRadius: 8,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    marginTop: 16,
  },
  loginButtonText: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: '500',
    fontSize: 14,
  },
  dividerContainer: {
    marginVertical: 24,
    alignItems: 'center',
  },
  dividerLine: {
    width: '100%',
    borderTopColor: '#d1d5db',
    borderTopWidth: 1,
  },
  dividerText: {
    fontSize: 12,
    color: '#6b7280',
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    marginTop: -12,
  },
  facialButton: {
    width: '100%',
    paddingVertical: 12,
    borderColor: '#2563eb',
    borderWidth: 2,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  facialButtonText: {
    color: '#2563eb',
    fontWeight: '500',
    fontSize: 14,
  },
  registrationPrompt: {
    marginTop: 24,
    alignItems: 'center',
  },
  promptText: {
    fontSize: 12,
    color: '#4b5563',
  },
  promptLink: {
    color: '#2563eb',
    fontWeight: '500',
  },
  scanningContainer: {
    paddingVertical: 32,
    alignItems: 'center',
  },
  scanningIconBox: {
    paddingHorizontal: 24,
    paddingVertical: 24,
    backgroundColor: '#dbeafe',
    borderRadius: 50,
    marginBottom: 16,
  },
  scanningTitle: {
    fontSize: 18,
    fontWeight: '500',
    color: '#111827',
    marginBottom: 8,
  },
  scanningSubtitle: {
    color: '#4b5563',
    fontSize: 12,
  },
  quickRegisterButton: {
    marginTop: 24,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#1f2937',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  quickRegisterText: {
    color: '#ffffff',
    fontWeight: '500',
    fontSize: 14,
  },
});
