import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f9ff',
  },
  scrollContent: {
    paddingVertical: 32,
  },
  card: {
    maxWidth: 400,
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    paddingHorizontal: 32,
    paddingVertical: 32,
    marginHorizontal: 'auto',
    marginTop: 32,
  },
  errorBox: {
    backgroundColor: '#fee2e2',
    borderColor: '#fca5a5',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 16,
  },
  errorText: {
    color: '#b91c1c',
    fontSize: 14,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  backButtonText: {
    color: '#4b5563',
    marginLeft: 8,
    fontSize: 14,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 32,
  },
  headerIcon: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#dbeafe',
    borderRadius: 50,
    marginBottom: 16,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#111827',
  },
  headerSubtitle: {
    color: '#4b5563',
    marginTop: 8,
    textAlign: 'center',
    fontSize: 13,
  },
  formContainer: {
    gap: 16,
    marginBottom: 24,
  },
  formGroup: {
    marginTop: 16,
  },
  label: {
    fontSize: 12,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 8,
  },
  input: {
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderColor: '#d1d5db',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    fontSize: 14,
  },
  pickerButton: {
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderColor: '#d1d5db',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#ffffff',
  },
  pickerButtonText: {
    fontSize: 14,
    color: '#111827',
  },
  pickerButtonPlaceholder: {
    color: '#9ca3af',
  },
  dropdownContainer: {
    borderColor: '#d1d5db',
    borderWidth: 1,
    borderRadius: 8,
    marginTop: 8,
    backgroundColor: '#ffffff',
  },
  dropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomColor: '#e5e7eb',
    borderBottomWidth: 1,
  },
  dropdownItemText: {
    fontSize: 14,
    color: '#111827',
  },
  facialContainer: {
    marginTop: 16,
    borderColor: '#d1d5db',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderRadius: 8,
    paddingHorizontal: 24,
    paddingVertical: 24,
    alignItems: 'center',
  },
  facialIconBox: {
    marginBottom: 12,
  },
  facialTitle: {
    fontSize: 13,
    fontWeight: '500',
    color: '#111827',
    marginBottom: 8,
    textAlign: 'center',
  },
  facialSubtitle: {
    fontSize: 12,
    color: '#4b5563',
    marginBottom: 16,
    textAlign: 'center',
  },
  captureButton: {
    paddingHorizontal: 24,
    paddingVertical: 8,
    backgroundColor: '#2563eb',
    borderRadius: 8,
  },
  captureButtonText: {
    color: '#ffffff',
    fontWeight: '500',
    fontSize: 13,
  },
  capturedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  capturedIconBox: {
    width: 64,
    height: 64,
    backgroundColor: '#dcfce7',
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  capturedText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#16a34a',
    marginLeft: 8,
  },
  submitButton: {
    width: '100%',
    paddingVertical: 12,
    backgroundColor: '#2563eb',
    borderRadius: 8,
    marginTop: 24,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  submitButtonText: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: '500',
    fontSize: 15,
  },
});
